FROM maven:3.6.3-openjdk-17-slim AS build

WORKDIR /app

COPY toolcomerce/pom.xml .

COPY toolcomerce/src ./src

RUN mvn clean package -DskipTests=true

FROM eclipse-temurin:17.0.8.1_1-jre-jammy

# FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file of your Spring Boot application into the container
COPY --from=build /app/target/toolcomerce-0.0.1-SNAPSHOT.jar /app/toolcomerce.jar

# Expose the port that your Spring Boot application is listening on (if needed)
EXPOSE 8081

# Specify the command to run your Spring Boot application
CMD ["java", "-jar", "toolcomerce.jar"]

